# Generated by Django 3.2.16 on 2024-07-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakwachPOS', '0002_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default_picture.jpg', upload_to='profile'),
        ),
    ]
