# Generated by Django 3.2.16 on 2024-07-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pakwachPOS', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belonging', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('unit_amount', models.IntegerField(default=0)),
                ('total_amount', models.FloatField(max_length=500)),
                ('status', models.CharField(default='available', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pakwachPOS.module')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='checkout', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pakwachPOS.product')),
            ],
        ),
    ]
