# Generated by Django 3.2.16 on 2024-07-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakwachPOS', '0005_auto_20240710_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='belonging',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='belonging',
            field=models.CharField(max_length=255),
        ),
    ]
