# Generated by Django 3.2.16 on 2024-07-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakwachPOS', '0006_auto_20240710_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_amount',
            field=models.FloatField(max_length=500),
        ),
    ]
