# Generated by Django 3.2.16 on 2024-07-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakwachPOS', '0007_auto_20240710_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
