# Generated by Django 3.2.16 on 2024-07-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakwachPOS', '0009_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='product',
        ),
        migrations.AddField(
            model_name='receipt',
            name='pdf',
            field=models.FileField(default=1, upload_to='', verbose_name='pdf-doc'),
            preserve_default=False,
        ),
    ]
