# Generated by Django 3.2.16 on 2024-07-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakwachPOS', '0011_receipt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='pdf',
            field=models.FileField(upload_to='file', verbose_name='pdf-doc'),
        ),
    ]
