# Generated by Django 3.2.16 on 2024-07-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pakwachPOS', '0012_alter_receipt_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dept_type', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
