# Generated by Django 3.2.16 on 2024-07-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pakwachPOS', '0014_userprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
    ]
