# Generated by Django 3.2.16 on 2024-07-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pakwachPOS', '0016_alter_userprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pakwachPOS.receipt'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(default='checked', max_length=200),
        ),
    ]
