# Generated by Django 3.2.16 on 2024-07-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pakwachPOS', '0017_auto_20240725_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_amount',
        ),
    ]
